### ISSUE TITLE
Is there a option to change the name of the generated file?

### ISSUE THREAD

**Issue by italovieira** [tinted-theming/tinty#1]
In [flavours](https://github.com/Misterio77/flavours), you can set the file that will be generated by setting the `file` option.
```toml
[[item]]
file = "~/.config/alacritty/colors.toml"
template = "alacritty"
```

Is there a equivalent option in tinty?
