### ISSUE TITLE
[Bug report] Applying a base16 theme in Alacritty sets bright variation of colours to be the same as normal

### ISSUE THREAD

**Issue by gridsystem** [tinted-theming/tinty#116]
## Describe the bug

- Applying a base16 theme sets bright variation of colours to be the same as normal
- But applying a base24 version of a theme sets the bright variation of colours to be brighter than normal

I apologise if I'm missing something here as I've only spent the one evening looking into Tinted and Tinty. I'm also not sure if I'm logging this in the right repo so please let me know if I have and I can put this in the right place.

I'm going for a standard ANSI 16 colour setup. I use Alacritty and Tmux. My $TERM outside of Tmux is `xterm` and inside of it it's `screen`.

When I apply a theme with Tinty i.e. `tinty apply base16-catppuccin-mocha`, it generates a `colors.toml` in which all of the colour codes for the bright variations of each colour match the normal colour codes except for black and white.

Interestingly when applying a base24 theme i.e. `tinty apply base24-catppuccin-mocha` it correctly generates different, brighter, colour codes for the 8 bright colours.

Do I need to run/configure something from the tinted-shell repo in addition to Tinty to get the behaviour I'm looking for?

## Expected behavior

When applying a base16 theme, Tinty should generate bright colour codes for Alacritty rather than duplicating the normal colour codes for bright colours.

## **System**

**Operating system:** MacOS

**Terminal:** Alacritty

## Minimal configuration file

```
# ~/.config/tinted-theming/tinty/config.toml
# Global settings
shell = "bash -c '{}'"

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/alacritty"
hook = "cp -f %f ~/.config/alacritty/colors.toml && touch ~/.config/alacritty/alacritty.toml"
supported-systems = ["base16", "base24"]
```

```
# alacritty.toml
[general]
import = ["~/.config/alacritty/colors.toml"]
```

**Comment by JamyGolden** [comment]
Hello, this is actually expected behaviour. Base16 only has the 16 colours (colours 0-7: 8 shades of grey and colours 8-16: red, orange, yellow, green, cyan, blue, purple, brown) - Here is some more info about it in the [styling spec](https://github.com/tinted-theming/home/blob/main/styling.md). Having only 1 shade of each non-grey-scale colour means that the brights are duplicated with that value.

With Base24, however, is a superset of Base16 with 8 extra colours (bright variants of the non-grey colours) which allows us to use unique colours for bright colours. Of course it's possible to dynamically adjust colours, but that's not something we've done in our templates for Base16 and Base24 at least since it's not expected behaviour from the spec which is well established at this point. We have spoken about doing something like this with a theme that takes just the first 8 ANSI colours and generating all other colours from there, but we haven't done this yet though but is on our radar.

I'd suggest using Tinty with the Alacritty themes in [tinted-terminal] template for your setup. Since it styles alacritty directly there's a lot less chance of some bug occurring (Especially while using tmux).

`config/tinted-theming/tinty/config.toml`:
```toml
shell = "zsh -c '{}'"
default-scheme = "base16-oceanicnext"

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-alacritty"
themes-dir = "themes/alacritty"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hook = "tmux run 2> /dev/null && tmux source-file %f"
themes-dir = "colors"
supported-systems = ["base16", "base24"]
```

and `config/alacritty/alacritty.toml`:

```toml
[general]
import = ["~/.local/share/tinted-theming/tinty/tinted-alacritty-themes-alacritty-file.toml"]
```

And if you happen to use neovim: https://github.com/tinted-theming/tinted-nvim has a `live_reload` option which checks the current Tinty theme and updates automatically when switched.
