### ISSUE TITLE
[Question] It will be possible to use custom templates?

### ISSUE THREAD

**Issue by italovieira** [tinted-theming/tinty#12]
Hi,

In flavours I used to use a [custom template for tmux](https://github.com/italovieira/dotfiles/blob/master/flavours/.config/flavours/templates/tmux/templates/custom.mustache).

I wonder if it will be possible to do that in tinty as well.

**Comment by JamyGolden** [comment]
Once I add the builder to Tinty this would be possible with tinty alone, but for now the best thing to do would be to build your template manually (you would just have to do this one time).

## 1. First change your directory structure to look like this:

```
- custom-tmux-template
  - templates
    - custom.mustache
    - config.yaml
```

config.yaml should have this content:

```yaml
default:
    extension: .conf
    output: colors
```

`custom-tmux-template` can be named anything.

## 2. Download and run base16-builder-go

Download the latest [builder-go binary](https://github.com/tinted-theming/base16-builder-go/releases) and run it inside your new template directory:

```shell
cd /path/to/custom-tmux-template
/path/to/base16-builder-go .
```

This should generate a `custom-tmux-template/colors` directory containing all of the themes.

## 3. Update Tinty config.toml

Now you just need to include this template in your tinty `config.toml` file:

```toml
[[items]]
path = "/path/to/custom-tmux-template"
name = "custom-tmux"
hook = "test -n \"$TMUX\" && tmux source-file %f"
themes-dir = "colors"
```

Let me know if you manage to get it working.
