### ISSUE TITLE
Support for emacs '-theme.el' files [Feature request] 

### ISSUE THREAD

**Issue by 1ynn1ei** [tinted-theming/tinty#30]
## Is your feature request related to a problem? Please describe.
It is good practice for emacs themes to end in the stub `-theme.el`. Current implementation of Tinty does not support this naming convention:
```rust
        let theme_dir = fs::read_dir(&themes_path)
            .map_err(anyhow::Error::new)
            .with_context(|| format!("Themes are missing from {}, try running `{} install` or `{} update` and try again.", item.name, REPO_NAME, REPO_NAME))?;
        let theme_option = &theme_dir.filter_map(Result::ok).find(|entry| {
            let path = entry.path();
            let filename = path.file_stem().and_then(|name| name.to_str());
            full_scheme_name == filename.unwrap_or_default()
        });
```
it checks for exact naming, which works for almost all applications.

## Describe the solution you'd like

Implementation of a file-name override in the .toml config which allows for exceptional cases:

```toml
[[items]]
name = "base16-emacs"
path = "https://github.com/belak/base16-emacs"
themes-dir="build"
file-override = "$(tinty current)-theme"
hook = "cp -f %f ~/.emacs.d/custom-theme.el && emacsclient -e '(load-theme 'custom t)'"
```

## Describe alternatives you've considered

Rebuilding & packaging the base16-emacs for consumption of a manager, instead of as an emacs package. This would allow foregoing of the `-theme.el` standard. This is not a desirable fix, but if the above functionality is out of scope of Tinty I can understand. 

## Additional context

If the suggested implementation is desirable I can work on the feature and test it. I would like to avoid having to fork the existing build for base16-emacs, if possible.
