### ISSUE TITLE
[Question] way detect if theme is light or dark

### ISSUE THREAD

**Issue by ckjoris** [tinted-theming/tinty#71]
**What version of `tinty` are you using?**
tinty 0.18.0

Hi, is there a way to detect if the current theme is dark or light, or just read the 'variant' from the theme file?

I want to script this detection, so could pass the appropriate theme argument to other cli tools.
 
Currently having to do a bit of a workaround in the shell handler:

```toml
# tinty config
[[items]]
name = "base16-shell"
path = "https://github.com/tinted-theming/base16-shell"
hook = "cat %f > ~/.base16_theme && using_tinty=true ~/dotfiles/base16_handler_shell.sh ; . %f"
```

```sh
# ~/dotfiles/base16_handler_shell.sh
# get the yaml file
yaml_path=$(tinty info "$(tinty current)" | grep -Poi '\@\K.*(.*.yaml)')
# strip the leading and trailing whitespaces
yaml_path=$(echo "$yaml_path" | xargs)

$(grep "variant" "$yaml_path" | grep --silent -i "light")
is_light=$?
echo "$is_light" >> ~/.base16_theme_light
```
