### ISSUE TITLE
[Bug report] text with the generated colors isn't very readable

### ISSUE THREAD

**Issue by salahoued** [tinted-theming/tinty#81]
## Describe the bug

I use `tinty` to generate `custom schemes` from the wallpaper, but `sometimes` the generated colors (base08-base0F) in a dark
color scheme aren't very readable when using `base00` as background color

## Expected behavior
When generating a dark color scheme the color from `base08` to `base0F` should be showing and readable with the backgroud `base00`, just like the foreground color `base07`. and those colors 'should' 'lighter'.

## Screenshots

![konsole](https://github.com/user-attachments/assets/d24c5061-ed83-4c1b-b2d8-afca8ac794ad)
![alacritty](https://github.com/user-attachments/assets/9520dc6f-2f0a-4c0c-8223-a678731449e8)

**Terminal:**
Konsole (most of the time) and alacritty

## Minimal configuration file

```toml
# Global settings
shell = "bash -c '{}'"
# default-scheme = "base16-mocha"
#hooks = [ "command1", "command2" ]

# Item configurations
[[items]]
name = "tinted-shell"
path = "~/.local/share/tinted-theming/tinty/repos/tinted-shell"
themes-dir = "scripts"
hook = "source %f"
supported-systems = ["base16"]

[[items]]
name = "base16-rofi"
path = "~/.local/share/tinted-theming/tinty/repos/base16-rofi"
themes-dir = "colors"
hook = "cp -r %f ~/.config/rofi/colors.rasi"

[[items]]
name = "base16-fzf"
path = "~/.local/share/tinted-theming/tinty/repos/base16-fzf"
themes-dir = "bash"
hook = "cp -r %f ~/.fzfcolors.sh && source ~/.fzfcolors.sh"
supported-systems = ["base16"]
```
