### ISSUE TITLE
## [Bug report] Invalid hexadecimal color format error for valid colors

### ISSUE THREAD

**Issue by screwyprof** [tinted-theming/tinty#82]
## Describe the bug

When running `tinty info base16-catppuccin-latte`, it throws an "invalid hexadecimal color format" error even though the YAML file contains valid hex colors:
```sh
❯ tinty info base16-catppuccin-latte
Catppuccin Latte (base16-catppuccin-latte) @ /Users/happygopher/.local/share/tinted-theming/tinty/repos/schemes/base16/catppuccin-latte.yaml
by https://github.com/catppuccin/catppuccin
Error: invalid hexadecimal color format
```

## Expected behavior

The command should display color information for the theme since all colors in the YAML are valid hex codes.

## Screenshots
N/A

## **System**
**Operating system:** macOS 15.1
**Terminal:** iTerm2

## Minimal configuration file
The YAML file at `~/.local/share/tinted-theming/tinty/repos/schemes/base16/catppuccin-latte.yaml`:

```yaml
system: "base16"
name: "Catppuccin Latte"
author: "https://github.com/catppuccin/catppuccin"
variant: "light"
palette:
  base00: "#eff1f5" # base
  base01: "#e6e9ef" # mantle
  base02: "#ccd0da" # surface0
  base03: "#bcc0cc" # surface1
  base04: "#acb0be" # surface2
  base05: "#4c4f69" # text
  base06: "#dc8a78" # rosewater
  base07: "#7287fd" # lavender
  base08: "#d20f39" # red
  base09: "#fe640b" # peach
  base0A: "#df8e1d" # yellow
  base0B: "#40a02b" # green
  base0C: "#179299" # teal
  base0D: "#1e66f5" # blue
  base0E: "#8839ef" # mauve
  base0F: "#dd7878" # flamingo
```

## Additional context
All hex colours in the YAML are valid 6-digit codes prefixed with #.
