### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by screwyprof** [tinted-theming/tinty#83]
## Describe the bug
When using a custom path for themes in `config.toml`, tinty still tries to find themes in the repos directory instead of using the configured custom path.

## Expected behavior
Tinty should use the custom path configured in `config.toml` for custom themes instead of defaulting to the repos directory.

## Screenshots
N/A

## **System**

**Operating system:** macOS 15.1
**Terminal:** iterm2

## Minimal configuration file
```toml
shell = "zsh -c '{}'"
default-scheme = "${theme}"
schemes-dir = "~/.local/share/tinted-theming/tinty/repos/schemes"

[[items]]
name = "bat"
path = "~/.config//tinted-theming/tinty/custom-schemes/bat"
themes-dir = "themes"
supported-systems = ["base16", "base24"]
hook = "cp -f %f ~/.config/bat/themes/gopher.tmTheme && bat cache --build"
```

## Additional context

```zsh
❯ tinty apply base24-dracula
Error: Failed to apply theme ""base24-dracula""

Caused by:
    Provided theme path for bat does not exist: /Users/happygopher/.local/share/tinted-theming/tinty/repos/bat/themes
    Try running `tinty install` or `tinty update` or check your config.toml file and try again.

❯ ls -al ~/.config/tinted-theming/tinty/custom-schemes
lrwxr-xr-x@ - happygopher 18 Nov 03:59  bat -> /nix/store/ffb4vis6bbd09b2vpkk551z81qswawcb-home-manager-files/.config/tinted-theming/tinty/custom-schemes/bat

❯ ls -al /nix/store/ffb4vis6bbd09b2vpkk551z81qswawcb-home-manager-files/.config/tinted-theming/tinty/custom-schemes/bat/themes
.r--r--r--@ 31k root  1 Jan  1970  base24-gopher.tmTheme
```
